name: Deploy Documentation to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    pages:
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Display Python version
              run: python -c "import sys; print(sys.version)"

            - name: Install build dependencies
              run: python -m pip install --upgrade pip setuptools wheel

            - name: Build and install
              run: |
                  mkdir -p _wlplan
                  python -m pip install -v .

            - name: Install docs dependencies
              run: python -m pip install sphinx sphinx_rtd_theme myst_parser

            - name: Build docs
              run: |
                  cd docs
                  make html
            
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: docs/build/html

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
